# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constr_test.xdc

# Block Designs: bd/design_test_1/design_test_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1 || ORIG_REF_NAME==design_test_1} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_xbar_0/design_test_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_xbar_0 || ORIG_REF_NAME==design_test_1_xbar_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_ps7_0_axi_periph_0/design_test_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_test_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_rst_ps7_0_50M_0/design_test_1_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_rst_ps7_0_50M_0 || ORIG_REF_NAME==design_test_1_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_processing_system7_0_1/design_test_1_processing_system7_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_processing_system7_0_1 || ORIG_REF_NAME==design_test_1_processing_system7_0_1} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_ENC_AES_0_0/design_test_1_ENC_AES_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_ENC_AES_0_0 || ORIG_REF_NAME==design_test_1_ENC_AES_0_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_Split_128_32_0_0/design_test_1_Split_128_32_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_Split_128_32_0_0 || ORIG_REF_NAME==design_test_1_Split_128_32_0_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_tier2_xbar_0_0/design_test_1_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_tier2_xbar_0_0 || ORIG_REF_NAME==design_test_1_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_tier2_xbar_1_0/design_test_1_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_tier2_xbar_1_0 || ORIG_REF_NAME==design_test_1_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_tier2_xbar_2_0/design_test_1_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_tier2_xbar_2_0 || ORIG_REF_NAME==design_test_1_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_auto_pc_0/design_test_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_auto_pc_0 || ORIG_REF_NAME==design_test_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_xlconcat_0_0/design_test_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_xlconcat_0_0 || ORIG_REF_NAME==design_test_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_xlconcat_0_1/design_test_1_xlconcat_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_xlconcat_0_1 || ORIG_REF_NAME==design_test_1_xlconcat_0_1} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_0_4/design_test_1_axi_gpio_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_0_4 || ORIG_REF_NAME==design_test_1_axi_gpio_0_4} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_0_5/design_test_1_axi_gpio_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_0_5 || ORIG_REF_NAME==design_test_1_axi_gpio_0_5} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_0_6/design_test_1_axi_gpio_0_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_0_6 || ORIG_REF_NAME==design_test_1_axi_gpio_0_6} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_0_7/design_test_1_axi_gpio_0_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_0_7 || ORIG_REF_NAME==design_test_1_axi_gpio_0_7} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_0_8/design_test_1_axi_gpio_0_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_0_8 || ORIG_REF_NAME==design_test_1_axi_gpio_0_8} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_0_9/design_test_1_axi_gpio_0_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_0_9 || ORIG_REF_NAME==design_test_1_axi_gpio_0_9} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_pt0_0/design_test_1_axi_gpio_pt0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_pt0_0 || ORIG_REF_NAME==design_test_1_axi_gpio_pt0_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_pt1_0/design_test_1_axi_gpio_pt1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_pt1_0 || ORIG_REF_NAME==design_test_1_axi_gpio_pt1_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_pt2_0/design_test_1_axi_gpio_pt2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_pt2_0 || ORIG_REF_NAME==design_test_1_axi_gpio_pt2_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_pt3_0/design_test_1_axi_gpio_pt3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_pt3_0 || ORIG_REF_NAME==design_test_1_axi_gpio_pt3_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_0_10/design_test_1_axi_gpio_0_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_0_10 || ORIG_REF_NAME==design_test_1_axi_gpio_0_10} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_0_11/design_test_1_axi_gpio_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_0_11 || ORIG_REF_NAME==design_test_1_axi_gpio_0_11} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_0_12/design_test_1_axi_gpio_0_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_0_12 || ORIG_REF_NAME==design_test_1_axi_gpio_0_12} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_0_13/design_test_1_axi_gpio_0_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_0_13 || ORIG_REF_NAME==design_test_1_axi_gpio_0_13} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_ct0_0/design_test_1_axi_gpio_ct0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_ct0_0 || ORIG_REF_NAME==design_test_1_axi_gpio_ct0_0} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_ct0_1/design_test_1_axi_gpio_ct0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_ct0_1 || ORIG_REF_NAME==design_test_1_axi_gpio_ct0_1} -quiet] -quiet

# IP: bd/design_test_1/ip/design_test_1_axi_gpio_ct0_2/design_test_1_axi_gpio_ct0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_test_1_axi_gpio_ct0_2 || ORIG_REF_NAME==design_test_1_axi_gpio_ct0_2} -quiet] -quiet

# XDC: c:/Users/innfe/Proiect_SSC/AES_Encrypted_HoneyPot/AES_Encrypted_HoneyPot.gen/sources_1/bd/design_test_1/design_test_1_ooc.xdc
