# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/innfe/Proiect_SSC/AES_Encrypted_HoneyPot/AES_Encrypted_HoneyPot.srcs/sources_1/bd/design_test_1/ip/design_test_1_xbar_0/design_test_1_xbar_0.xci
# IP: The module: 'design_test_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/innfe/Proiect_SSC/AES_Encrypted_HoneyPot/AES_Encrypted_HoneyPot.gen/sources_1/bd/design_test_1/ip/design_test_1_xbar_0/design_test_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_test_1_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/innfe/Proiect_SSC/AES_Encrypted_HoneyPot/AES_Encrypted_HoneyPot.srcs/sources_1/bd/design_test_1/ip/design_test_1_xbar_0/design_test_1_xbar_0.xci
# IP: The module: 'design_test_1_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/innfe/Proiect_SSC/AES_Encrypted_HoneyPot/AES_Encrypted_HoneyPot.gen/sources_1/bd/design_test_1/ip/design_test_1_xbar_0/design_test_1_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_test_1_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
